### ISSUE TITLE
Non-overlapping Intervals 

### ISSUE THREAD

**Issue by Anjani27** [AryanBarsaiyan/DSA_CP_Webd_Project_hacktoberfest2022#30]
Hi, @AryanBarsaiyan  I would like to contribute to this repo and will to add solution of one of the DP problem which is Non-overlapping Intervals. I would be more than happy if you assign this to me under Hacktoberfest2022 .
Thanks!!

**Comment by AryanBarsaiyan** [comment]
Not accepting CPP/C DSA codes    
Alternative ->   
1)Create a page using HTML & CSS Add DSA problem statement and solution in that    
2)You can contribute in python and java OR
  Ask for an issue assign.  
3)Add any web Project.
